### ISSUE TITLE
Sound packs for 2.6 Santa are not displayed

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/buddy#16]
Seemes like sounds packs are not deisplayed for 2.6 (while other options work okay)

2.6
![Screenshot 2022-02-15 at 09 49 45](https://user-images.githubusercontent.com/46420768/154026313-c1083e2e-635d-428e-aee9-9b3833dc4998.png)

Others
![Screenshot 2022-02-15 at 09 49 30](https://user-images.githubusercontent.com/46420768/154026357-49c3e5e3-d38c-45dd-803d-ab3378db032a.png)
![Screenshot 2022-02-15 at 09 49 57](https://user-images.githubusercontent.com/46420768/154026371-b167108d-0e4a-451f-90ee-6f84906722ad.png)

**Comment by freshollie** [comment]
There is no tag for the v2.6 sounds, so this is working as expected :/. What would you want to do in this scenario?

**Comment by JimB40** [comment]
Repair tag?

**Comment by freshollie** [comment]
Think we discussed in discord to show the latest in this case? Or the next lower version? I wasn't sure what your preference was, but happy to put in a fix for this now. Though would be nice if we tagged Sound packs alongside our SD Card pack releases.

**Comment by JimB40** [comment]
So what is tagging and who, when & how during production should apply it?
Simple bugs postoned few days will postpone themseselves forever or be forgotten until someone else open same issue after year.
Next lower version maybe with short info on top "using version ..."

**Comment by freshollie** [comment]
https://github.com/EdgeTX/edgetx-sdcard-sounds should have the latest version of the sounds tagged with `v2.6.0`, but I will do what you suggest and use the next lower version
