### ISSUE TITLE
Unable to flash protected devices

### ISSUE THREAD

**Issue by vbabiy** [EdgeTX/buddy#20]
I get this error:

```Special DfuSe command 65 failed Details```

My Setup:
```
OS: Manjaro Linux x86_64
Host: X570 I AORUS PRO WIFI -CF
Kernel: 5.15.21-1-MANJARO
Uptime: 1 day, 8 hours, 21 mins
Packages: 2243 (pacman), 39 (flatpak), 9 (snap)
Shell: zsh 5.8
Resolution: 2560x1440, 2560x1440, 2560x1440, 2560x1440
DE: GNOME 41.3
WM: Mutter
WM Theme: Qogir-dark
Theme: Qogir [GTK2/3]
Icons: Qogir [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: AMD ATI Radeon Pro WX 4100
Memory: 20919MiB / 64316MiB
```

**Comment by freshollie** [comment]
Hey! Could you send a screenshot?

**Comment by freshollie** [comment]
Also might be helpful if you could screenshot the JS console when you get the error, and would be good to know your hardware

**Comment by vbabiy** [comment]
![image](https://user-images.githubusercontent.com/15382/155422693-e639f3a1-1423-4d59-b9cf-a4b1cf125be1.png)

![image](https://user-images.githubusercontent.com/15382/155422673-d7c2dfec-35df-4b88-a17f-ad7b6778c782.png)

![image](https://user-images.githubusercontent.com/15382/155422727-dd74f975-e909-4eb4-ab5c-ba1dc6cb47d3.png)
![image](https://user-images.githubusercontent.com/15382/155422819-cea4e4cc-6e49-4e0b-aa01-f1d4686ca831.png)

**Comment by freshollie** [comment]
So it's failing to run the DFuse command to erase a sector from your radio, I've pushed a change which might give some more info on the error. Can you try that again in about 30 mins when the build goes live?

**Comment by vbabiy** [comment]
@freshollie Looks like I got the same output: 
![image](https://user-images.githubusercontent.com/15382/155440917-087b06be-381d-4a77-9c46-a19a20bd4faa.png)

**Comment by vbabiy** [comment]
Also when I try to use the edgetx-flasher (The desktop version) I get this error: 
![image](https://user-images.githubusercontent.com/15382/155441184-259b07e9-18ec-44a1-9487-015b145140b3.png)

**Comment by freshollie** [comment]
So we think this issue is become of write protection in some radio models, in Flasher you can correctly flash your radio by enabling `Force flashing`. For Buddy this is not yet available. Can you try this?

**Comment by vbabiy** [comment]
![image](https://user-images.githubusercontent.com/15382/158397459-915c29d2-2d6d-4a34-a560-93b15cae5f14.png)
![image](https://user-images.githubusercontent.com/15382/158397498-38f40746-d522-42bd-b136-f7d6f81029d7.png)

@freshollie if I did it right, looks like the same issue

**Comment by pfeerick** [comment]
Once you've done the force unprotect, try flashing the firmware a second time... (shouldn't need the force unprotect... i.e. if it actually did it's job, buddy should work now). Basically the dfu-util tool needs to be run twice... first time clears the flag, second time does the actual firmware update.

**Comment by vbabiy** [comment]
@pfeerick indeed that seems to be working now.
![image](https://user-images.githubusercontent.com/15382/158592607-0552aa12-e22f-4133-b8dc-8b6257b351fb.png)

**Comment by freshollie** [comment]
Nice! Will look into automatically unlocking protected devices

**Comment by freshollie** [comment]
Thanks for the report, if this happens to others they will be prompted to use the new "Unlocker" tool
![image](https://user-images.githubusercontent.com/11363036/160113412-557b5ba8-92d9-4955-9342-47fdbd5ee74e.png)
![image](https://user-images.githubusercontent.com/11363036/160113456-2285038f-a826-40f8-99f7-d49ed484ffcd.png)

At some point I will build this into the main flashing flow without having to redirect to a new tool
