### ISSUE TITLE
Selection of radio is broken on SD Card

### ISSUE THREAD

**Issue by vbabiy** [EdgeTX/buddy#29]
![image](https://user-images.githubusercontent.com/15382/179721494-20454a8e-c41b-419c-9bf5-0d05fbdd6e98.png)

**Comment by vbabiy** [comment]
This happens if you try to scroll through the list a couple of times.

**Comment by freshollie** [comment]
Hey, thanks for reporting. This seems to be a problem in the sdcard manifest with the new radios coming in. Need to work out how I can uniquely address these targets.

**Comment by freshollie** [comment]
https://github.com/EdgeTX/buddy/pull/31 should ensure this doesn't happen again even if the manifest is broken
