### ISSUE TITLE
Downloading and flashing nightlies

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/buddy#32]
So it seems like it's not possible to download and flash nightlies atm? So what did I break this time? 😆  I tried this with a newly added target, as well as old ones, and seem to thing I had the same problem at one point with a PR build, but can't be certain as it was a while ago that I tried. However flashing from a release seems to be fine.

**Comment by pfeerick** [comment]
And it looks like my upload speed is foobar atm so it took a while for this paltry 2.5MB screen record to upload...
https://user-images.githubusercontent.com/5500713/179895342-4456c22e-7d9c-4379-b2df-4f672099a467.mp4

**Comment by freshollie** [comment]
Nice catch. Looks like this is because you have moved the targets into a sub directory within the zip? I will put out a fix.

**Comment by pfeerick** [comment]
Hm... it wasn't intentional, so probably a change somewhere in the github actions... I'll give it a try soon. If I manage to put a finger on the cause, and revert it to not have the subfolder, will it break anything then? 😆

**Comment by freshollie** [comment]
The change I have in the PR will handle any subfolders no no subfolders. Zip files don't technically have a file system, so when I was reading the names of extracted files I was trying to find the firmware name without assuming there could be anything in the path before.

**Comment by pfeerick** [comment]
Much appreciated, and you'll be please to know it's working perfectly now :) I'm still not sure what changed as I suspected it would be the upload action since a new release came out with some changes a few days ago, but it's version locked so it can't be that. It's been like this for a while it seems as I have a nightly from end of February that is the same (with a subfolder)... so I wonder if anyone actually ever used it to flash them! 😆
