### ISSUE TITLE
Firmware flash unable to load radio models.

### ISSUE THREAD

**Issue by JarrodB92** [EdgeTX/buddy#42]
I tried flashing firmware using EdgeTX buddy on two computers and two different browsers and both were stating they could not load radio models.
Thanks.

**Comment by freshollie** [comment]
Fixed. Was a problem with a server. Thanks for the report.

**Comment by JarrodB92** [comment]
You all are incredible!

**Comment by Zirby13** [comment]
ничего там не исправленно, нельзя выбрать модель радио!
