### ISSUE TITLE
Disable "Include pre-releases"

### ISSUE THREAD

**Issue by woutput** [EdgeTX/buddy#47]
After enabling "Include pre-releases", I can't disable it anymore. Using Google Chrome Version 115.0.5790.110 (Official Build) (64-bit).
I think it's not a big thing, but maybe not so nice...

Thanks for this great software!
Woutput

**Comment by woutput** [comment]
Update:
Steps to reproduce:
1. Enable "Include pre-releases"
2. Select (one of) the pre-release
3. Try to disable "Include pre-releases"

What does work:
1. Enable "Include pre-releases"
2. Select one of the older releases
3. Disable "Include pre-releases"

**Comment by freshollie** [comment]
Very interesting. I will try and change the behaviour to allow this

**Comment by raphaelcoeffic** [comment]
Seems to work properly now.
