### ISSUE TITLE
QoL: Ensure user knows how to DFU mode flash

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/buddy#52]
Stage two (connect radio) should probably have a message that informs the user that their radio should be either OFF or DFU button held down on connection (if their radio has that requirement - e.g. TPro, T20, NV14/EL18, PL18).

**Comment by Nezteb** [comment]
Agreed!

I spent an hour earlier unable to figure out how to correctly flash my new Boxer ELRS with the latest version of EdgeTX. I kept getting errors about there being no DFU interface:
![2024-03-10 19_36_53-EdgeTX Buddy](https://github.com/EdgeTX/buddy/assets/3588798/78696c94-c63e-47f2-8822-94ca78477ee8)

Searching online for "Device does not have any USB DFU interfaces" only pulled up some obscure RC forums of people who already know what they are talking about. I'm very new to this hobby, so this would be a huge help for other newcomers.

**Comment by pfeerick** [comment]
One possibility is to simply extend text here (and it's translated derivatives)
https://github.com/EdgeTX/buddy/blob/530cf358eb279e16f3c77a15db9f8db2b840317b/src/renderer/components/devices/DeviceSelector.tsx#L157

i.e. 
> Add a device to get started

could become 

> Add a device to get started
> 
> Ensure your radio is turned off when connecting the USB, and that you pressed the boot0/DFU button while connecting the USB if this was a requirement to enter DFU mode for your radio. 

Maybe also worth showing a link to the EdgeTX manual page for more information - either on this page or the next - for troubleshooting steps and more information about which radios need DFU mode TLC. Do we need to be more explicit and tell the user to look for the STM32 Bootloader entry?

![image](https://github.com/EdgeTX/buddy/assets/5500713/83df5564-1d28-45d5-b215-d58b94ebcf93)
