### ISSUE TITLE
Unable to click Settings or GitHub icon in App

### ISSUE THREAD

**Issue by Pancronos** [EdgeTX/buddy#60]
Don't know why but the app on windows 11 doesn't let me open settings. if i click on the github icon or the setting icon doesn't do anything. It works fine online.
Even running as administrator doesn't work.

**Comment by pfeerick** [comment]
Reproducible for me on Win11, haven't tried on Linux.

**Comment by freshollie** [comment]
I don't have windows 11 to test this on. @riwanou maybe you can work this out?

**Comment by raphaelcoeffic** [comment]
> I don't have windows 11 to test this on. @riwanou maybe you can work this out?

No dev using with Windows 😅

**Comment by raphaelcoeffic** [comment]
Btw. I'm seeing this on my local build with #77. I will try to find out what is happening. From what I've checked, it is non-obvious.
