### ISSUE TITLE
No Jumper T-lite V2

### ISSUE THREAD

**Issue by zandorsp** [EdgeTX/buddy#78]
The buddy have only Jumper T-lite. Not the Jumper T-lite v2:

![Captura de tela de 2024-04-07 17-30-07](https://github.com/EdgeTX/buddy/assets/53715440/529f7aad-ab2f-4c9c-b0e0-207a4aa24118)

**Comment by raphaelcoeffic** [comment]
@zandorsp AFAIK, there is no special "T-lite v2" firmware.

**Comment by pfeerick** [comment]
Correct, both T-Lite and T-Lite V2 are handled by same firmware - there is no special treatment requiring seperate firmwares.
